CREATE TABLE SAMPLE_TABLE (
ID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
COLUMN1 BIGINT,
COLUMN2 DECIMAL(15,2),
COLUMN3 VARCHAR(3),
CREATETIME TIMESTAMP
);